### ISSUE TITLE
[FEAT] Add workflows for CICD

### ISSUE THREAD

**Issue by khm0930** [khm0930/airflow-dev#1]
## What
- 개발 환경을 git hub aciton 으로  배포환경에 똑같이 구축

## Why
- 환경구축을 하게되면 최소 20분 가량 소비 되지만 자동화 구축되었을시 최대 4분 내외로 예상 됨

## How
- git hub action 으로 cicd 구축

## To-Do
- [x] .github workflow 디렉토리 생성
- [x]  yaml 파일생성
- [x] 레포에 필요한 vars,secrets 생성
- [x] actions test or yaml 파일 수정 

## Reference
-
